In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [183]:
df = pd.read_csv('/content/Combined_financial_sentiment_analysis_data.csv')
df = df.iloc[:,1:]

In [100]:
df.sample(10)

                                                    text label_text  label
6285   $MSFT - Microsoft: A Deep Due Diligence Dive O...    neutral      1
8020   U.S. Working ‘Closely’ With China on Virus Res...    neutral      1
12191  Hedge Funds Have Never Been This Bullish On Pa...   positive      2
6067   Former Celadon Employees, Drivers Describe Cha...    neutral      1
217    Sears' Eddie Lampert looks to regain full owne...    neutral      1
6578   Arm yourself with live #marketanalysis, #inves...    neutral      1
8880   NTSB wants Boeing to redesign 737s after deadl...    neutral      1
4815   Credit Suisse Chairman Says He Has a Lot of Sh...    neutral      1
13041  Edited Transcript of ALPHA.AT earnings confere...    neutral      1
10831  $BPIRY - Piraeus Bank S.A. (BPIRY) CEO Christo...    neutral      1

In [178]:
# Data cleaning pipeline
def clean_text(df, col ):

  """lowercasing"""
  df[col] = df[col].str.lower()

  """stripping"""
  df[col] = df[col].str.strip()

  """ Removing HTML tag if any"""
  from bs4 import BeautifulSoup
  df[col] = df[col].apply(
                          lambda x: BeautifulSoup(str(x), 'html.parser').get_text()
                          )
  import re
  df[col] = df[col].apply(
                        lambda x : re.sub(r'https?://\S+|www\.\S+', '', x)
                    )
  """Removing ticker"""

  df[col] = df[col].apply(
      lambda x: re.sub(r'\$[A-Za-z]+','<TICKER>',x))

  """Remove hashtags"""
  df[col] = df[col].apply(
      lambda x: re.sub(r'\#[A-Za-z]+','<Hashtag>',x))

  """Removing extra commas,inverted commas"""
  df[col] = df[col].apply(
      lambda x : re.sub(r"``\s*(.*?)\s*''",r'\1',x))

  """Spell correction"""
  from textblob import TextBlob
  df[col] = df[col].apply(
      lambda x: TextBlob(x).correct().string)

  """Emojis Handling"""
  import emoji
  df[col] = df[col].apply(
      lambda x : emoji.demojize(x)
  )

  return df

In [125]:
# Libraries for HTML tag and URL removal
from bs4 import BeautifulSoup
import re

In [126]:
df['text'].apply(
    lambda x: BeautifulSoup(str(x), 'html.parser').get_text()
    )

0        hedge funds have never been less bullish on md...
1        {free} macro week in review/preview november 2...
2        frequency therapeutics eps misses by $0.05, mi...
3        : nonfarm payroll revisions- october revised t...
4        nat gas prices plunge on milder weather, ample...
                               ...
14190    the best-performing cefs ytd - november 2019. ...
14191    hedge funds are souring on amag pharmaceutical...
14192     (+4.8% pre) teva pharma (teva), generics make...
14193      - softbank backs brazilian e-commerce softwa...
14194     - aurinia's successful study in lupus nephrit...
Name: text, Length: 14195, dtype: object

In [127]:
print(df['text'].head().to_string())

0    hedge funds have never been less bullish on md...
1    {free} macro week in review/preview november 2...
2    frequency therapeutics eps misses by $0.05, mi...
3    <TICKER>: nonfarm payroll revisions- october r...
4    nat gas prices plunge on milder weather, ample...

In [128]:

# Example long URL
long_url = "gihg u g  o https://huggingface.co/datasets/takala/financial_phrasebank  josdjp http"

In [129]:
# Removing Urls
re.sub( r'https?://\S+|www\.\S+', '', long_url)
df['text'].apply(
    lambda x : re.sub(r'https?://\S+|www\.\S+', '', x)
)

0        hedge funds have never been less bullish on md...
1        {free} macro week in review/preview november 2...
2        frequency therapeutics eps misses by $0.05, mi...
3        <TICKER>: nonfarm payroll revisions- october r...
4        nat gas prices plunge on milder weather, ample...
                               ...
14190    the best-performing cefs ytd - november 2019. ...
14191    hedge funds are souring on amag pharmaceutical...
14192    <TICKER> (+4.8% pre) teva pharma (teva), gener...
14193    <TICKER> <TICKER> - softbank backs brazilian e...
14194    <TICKER> - aurinia's successful study in lupus...
Name: text, Length: 14195, dtype: object

In [130]:
clean_text(df,'text')

                                                    text label_text  label
0      hedge funds have never been less bullish on md...   negative      0
1      {free} macro week in review/preview november 2...    neutral      1
2      frequency therapeutics eps misses by $0.05, mi...   negative      0
3      : nonfarm payroll revisions- october revised t...   positive      2
4      nat gas prices plunge on milder weather, ample...   negative      0
...                                                  ...        ...    ...
14190  the best-performing cefs ytd - november 2019. ...    neutral      1
14191  hedge funds are souring on amag pharmaceutical...   negative      0
14192   (+4.8% pre) teva pharma (teva), generics make...   positive      2
14193    - softbank backs brazilian e-commerce softwa...    neutral      1
14194   - aurinia's successful study in lupus nephrit...   positive      2

[14195 rows x 3 columns]

In [131]:
df['text'].sample(30).tolist()

['the shares shall be repurchased through public trading , for which reason the shares are repurchased otherwise than in proportion to the holdings of the shareholders .',
 'investors are shrugging off weak data and trade snags that would have roiled markets just months ago',
 'edited transcript of cio earnings conference call or presentation 1-nov-19 3:00pm gmt',
 ' (+0.0% pre) el paso electric and iif move towards final steps in acquisition process - ctfn',
 'apple is worth more than the entire s&p 500 energy index combined, including industry titans like exxon and chevron',
 "modern monetary theory: it's an unconventional economic theory made popular by progressive politicians alexandria o…",
 'credit suisse chairman says he has a lot of shareholder support',
 'equity rotations and the value of industrials',
 'virus uncertainty weighs on global shares - news.com.au',
 'the decision will have to be made whether the group agrees to the import of estonian meat and meat products to finland , the paper added .',
 'karvy case: sat asks sebi to hear axis bank’s plea, pass order within 15 days',
 'does the teradata corporation (nyse:tdc) share price fall with the market?',
 'crisis is rocking latin america. peru is an island of uneasy calm.',
 "ford's electric suv impresses credit suisse",
 'hedge funds have never been less bullish on westlake chemical corporation (wlk)',
 'healthy diets are out of reach for millions of people. #nutrition-smart agriculture makes healthy foods more afford…',
 'where the world is going',
 'a few employees would remain at the oulu plant in support functions for other group units .',
 'eagle point nii in-line, misses on total investment income',
 'royal dutch shell plc transaction in own shares #royaldutchshell #stock #marketscreener',
 '@tictoc trump warning by trump appointment of military departments leaders now trump can control them and tell them…',
 'my wife is 61 and earns $50,000. i’m 65 and earn $400,000 and will work until 71. should my wife take her social se…',
 "in the meantime the ceo 's duties will be assumed by outotec 's deputy ceo seppo rantakari .",
 ' - pareteum +8% after ceo termination',
 'he joined rautakirja in 1997 to lead one of its four business areas and took up the position of president and ceo in 2001 .',
 'cases involving rs 3.75 lakh crore disposed of at ibc pre-admission stage',
 'eagles going to be running 4 te sets lol',
 '1:com   - copper pops to biggest gain in six years on stimulus bet',
 'l brands stock price target cut to $16 from $20 at wedbush',
 'walmart has announced that it plans to open 500 new stores in china over the next five to seven years. that would m…']

In [132]:
'⚡️ “most people choose to support environment and healthcare organizations”\n\n'

'⚡️ “most people choose to support environment and healthcare organizations”\n\n'

In [114]:
"merrill lynch analyst campbell morgan upgraded his recommendation on paperlinx from `` neutral '' to `` buy '' in may "

"merrill lynch analyst campbell morgan upgraded his recommendation on paperlinx from `` neutral '' to `` buy '' in may "

In [123]:
re.sub(r"``\s*(.*?)\s*''",r'\1',"merrill lynch analyst campbell morgan upgraded his recommendation on paperlinx from `` neutral '' to `` buy '' in may")

'merrill lynch analyst campbell morgan upgraded his recommendation on paperlinx from neutral to buy in may'

In [175]:
df['text'].sample(30).tolist()

['the consumer economy continues to shrug off industry’s woes',
 'brazil pushes its great downsizing and rakes in $5.2 billion',
 "it's rate decision day in israel – here's what to expect",
 '- bear market bounce - j.c. parets returns to alpha trader.    ',
 '3 top schwab mutual funds for 2020',
 'stock market update: amazon and microsoft hit new highs',
 'what happened in the world economy this week – in charts (via @doubletgolle & @zschneeweiss)',
 'alnylam pharmaceuticals reports fourth quarter and full year 2019 financial results and highlights recent period activity',
 ':cur   - gold closing in on $1,700',
 "paul wolfowitz's nyt op-ed: blatherings of a sanctimonious sicko",
 'earning $40,000 a year in omaha used to be enough to make rent comfortably. not anymore.',
 'the agreement includes application maintenance and support services .',
 'the days of extraordinary market returns are over, says blackrock',
 'seazen : continuing connected transactions 2020 services framework agreement   …',
 ': motorcar parts of america reports q3 eps of $0.28 vs $0.43 s&p capital iq consensus; revs +1.2% yr/yr to...',
 'next boe governor makes city access plea to brussels',
 'london stock exchange : notice of satisfaction and discharge   …',
 'chris matthews asks gabbard: why are so many democrats war hawks?',
 "company logos vanish from prince andrew's website as sex scandal grows",
 'upm stock fell 3 percent to euro 12.49 $ 17.24 in early afternoon trading in helsinki .',
 'here are some of the business tax credits congress could approve by year’s end',
 "update 1-singapore's pavilion cancels u.s. lng cargo loading as market faces oversupply",
 "united joins delta and american in suspending flights between the u.s. and mainland china. united's flight suspensi...",
 "disappointed by the size of your social security check? you're not alone.",
 'vodafone idea, bharti rally on plan to increase mobile tariffs',
 '- karuna therapeutics (krtx) presents at piper jaffray healthcare conference - slideshow. read more and get u…',
 'arch coal rated buy at benchmark, seeing opportunity after selloff',
 "amazon's record 2019 in 7 metrics",
 '- luminex q1 revenue tops guidance; shares up 7% after hours',
 'among the scandinavian companies present in st. petersburg , is also named the swedish concern ncc , which implements projects in the field of asphalt production , road and housing construction ( project swedish krona ) .']

In [179]:
'bofa: "the gradual pickup in wage growth should keep the committee cautiously optimistic and overheating the econom…'
from textblob import TextBlob
TextBlob("Thier was a buisness annoucement yesturday about the new invesment oppurtunity in teh market.").correct().string

'Her was a business announcement yesterday about the new investment opportunity in the market.'

In [155]:
! pip install emoji
import emoji

Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 10.7 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.15.0

In [176]:
emoji.demojize('⚡️ “most people choose to support environment and healthcare organizations”\n\n')

':high_voltage: “most people choose to support environment and healthcare organizations”\n\n'

# Data Cleaning is Done

In [252]:
# Data cleaning pipeline
def clean_text(df, col ):

  """lowercasing"""
  df[col] = df[col].str.lower()

  """stripping"""
  df[col] = df[col].str.strip()

  import re
  df[col] = df[col].apply(
                        lambda x : re.sub(r'https?://\S+|www\.\S+', '', x)
                    )
  """Removing ticker"""

  df[col] = df[col].apply(
      lambda x: re.sub(r'\$[A-Za-z]+','<TICKER>',x))

  """Remove hashtags"""
  df[col] = df[col].apply(
      lambda x: re.sub(r'\#[A-Za-z]+','<Hashtag>',x))

  """Removing extra commas,inverted commas"""
  df[col] = df[col].apply(
      lambda x : re.sub(r"``\s*(.*?)\s*''",r'\1',x))

  """Emojis Handling"""
  import emoji
  df[col] = df[col].apply(
      lambda x : emoji.demojize(x)
  )

  df[col] = df[col].str.replace("...",".").str.replace("..",".").str.replace(".....…",".").str.replace("…",".")

  """Removing @"""
  df[col] = df[col].apply(
      lambda x : re.sub(r'(@[A-Za-z0-9]*)','',x)
  )

  # Removing ascii charcaters
  df[col] = df[col].apply(
      lambda x : re.sub('[""''—]','',x)
  )

  return df

In [253]:
clean_text(df,'text')

                                                    text label_text  label
0      hedge funds have never been less bullish on md...   negative      0
1      {free} macro week in review/preview november 2...    neutral      1
2      frequency therapeutics eps misses by $0.05, mi...   negative      0
3      <ticker>: nonfarm payroll revisions- october r...   positive      2
4      nat gas prices plunge on milder weather, ample...   negative      0
...                                                  ...        ...    ...
14190  the best-performing cefs ytd - november 2019. ...    neutral      1
14191  hedge funds are souring on amag pharmaceutical...   negative      0
14192  <ticker> (+4.8% pre) teva pharma (teva), gener...   positive      2
14193  <ticker> <ticker> - softbank backs brazilian e...    neutral      1
14194  <ticker> - aurinia's successful study in lupus...   positive      2

[14195 rows x 3 columns]

In [244]:
df['text'] = df['text'].str.replace("econom",'economy')

In [258]:
df.to_csv("Cleaned_Combined_financial_sentiment_analysis_data.csv")

In [257]:
df['text'].sample(5).tolist()

['best buy stock price target raised to $105 from $86 at oppenheimer',
 'operating profit totalled eur 9.6 mn , down from eur 42.0 mn the year before .',
 'edited transcript of aspn earnings conference call or presentation 31-oct-19 9:00pm gmt',
 'peck',
 'the real estate company posted a net loss of +ó  x201a -¼ 59.3 million +ó  x201a -¼ 0.21 per share compared with a net profit of +ó  x201a -¼ 31 million +ó  x201a -¼ 0.11 per share for the corresponding quarter of 2007 .']

In [240]:
re.sub(r'(@[A-Za-z0-9]*)','',"the second mouse gets the cheese @jeffcooperlive")

'the second mouse gets the cheese '

In [249]:
print(df['text'].str.contains('[""''—]', regex=True).sum())

293