In [99]:
import pandas as pd
import  numpy as np

In [15]:
from datasets import load_dataset

# 1. Load Financial PhraseBank using the updated parquet repository
print("--- Loading Financial PhraseBank (Parquet Fix) ---")
# This repository defaults to the full 'sentences_allagree' configuration (~2,264 sentences)
phrasebank = load_dataset("FinanceMTEB/financial_phrasebank")

print(f"PhraseBank Structure: {phrasebank}")
print(f"Total Rows: {len(phrasebank['train'])}")
print("First Row Example:")
print(phrasebank['train'][0])
print("PhraseBank Features (Columns):", phrasebank['train'].features)


print("\n" + "="*50 + "\n")


# 2. Load Twitter Financial News completely isolated
print("--- Loading Twitter Financial News ---")
twitter_news = load_dataset("zeroshot/twitter-financial-news-sentiment")

print(f"Twitter Dataset Structure: {twitter_news}")
print(f"Train Split Rows: {len(twitter_news['train'])}")
print(f"Validation Split Rows: {len(twitter_news['validation'])}")
print("First Row Example (Train):")
print(twitter_news['train'][0])
print("Twitter Features (Columns):", twitter_news['train'].features)

--- Loading Financial PhraseBank (Parquet Fix) ---

README.md:   0%|          | 0.00/465 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/104k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/80.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/1264 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

PhraseBank Structure: DatasetDict({
    train: Dataset({
        features: ['text', 'label_text', 'label'],
        num_rows: 1264
    })
    test: Dataset({
        features: ['text', 'label_text', 'label'],
        num_rows: 1000
    })
})
Total Rows: 1264
First Row Example:
{'text': 'The Samsung Mobile Applications Store was launched in January 2009 by Samsung Mobile Innovator , a program which enables mobile software developers to create applications for use across Samsung mobile devices .', 'label_text': 'neutral', 'label': 1}
PhraseBank Features (Columns): {'text': Value('string'), 'label_text': Value('string'), 'label': Value('int64')}

==================================================

--- Loading Twitter Financial News ---

README.md:   0%|          | 0.00/1.39k [00:00<?, ?B/s]

sent_train.csv:   0%|          | 0.00/859k [00:00<?, ?B/s]

sent_valid.csv:   0%|          | 0.00/217k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/9543 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/2388 [00:00<?, ? examples/s]

Twitter Dataset Structure: DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 9543
    })
    validation: Dataset({
        features: ['text', 'label'],
        num_rows: 2388
    })
})
Train Split Rows: 9543
Validation Split Rows: 2388
First Row Example (Train):
{'text': '$BYND - JPMorgan reels in expectations on Beyond Meat https://t.co/bd0xbFGjkT', 'label': 0}
Twitter Features (Columns): {'text': Value('string'), 'label': Value('int64')}

In [23]:
phrasebank['train'][0]

{'text': 'The Samsung Mobile Applications Store was launched in January 2009 by Samsung Mobile Innovator , a program which enables mobile software developers to create applications for use across Samsung mobile devices .',
 'label_text': 'neutral',
 'label': 1}

In [34]:
print(pd.DataFrame(twitter_news['train']).head().to_string())

                                                                                                     text  label
0                           $BYND - JPMorgan reels in expectations on Beyond Meat https://t.co/bd0xbFGjkT      0
1  $CCL $RCL - Nomura points to bookings weakness at Carnival and Royal Caribbean https://t.co/yGjpT2ReD3      0
2          $CX - Cemex cut at Credit Suisse, J.P. Morgan on weak building outlook https://t.co/KN1g4AWFIb      0
3                                             $ESS: BTIG Research cuts to Neutral https://t.co/MCyfTsXc2N      0
4                                 $FNKO - Funko slides after Piper Jaffray PT cut https://t.co/z37IJmCQzB      0

# Converting each data into data frame and then combining them

In [59]:
 # Financial data
df_fin = pd.DataFrame(phrasebank['train'])
df_fin_test = pd.DataFrame(phrasebank['test'])
df_fin

                                                   text label_text  label
0     The Samsung Mobile Applications Store was laun...    neutral      1
1     F-Secure , a developer of security solutions a...    neutral      1
2     The company serves customers in various indust...    neutral      1
3     The company reported net sales of 302 mln euro...    neutral      1
4     Microsoft last week also issued the first patc...    neutral      1
...                                                 ...        ...    ...
1259  Unbelievably , the company that makes them - F...    neutral      1
1260  Componenta has production lines for similar-si...    neutral      1
1261  Mr Ashley , deputy executive chairman of Sport...    neutral      1
1262  The building will house product development an...    neutral      1
1263  The fixed acquisition price amounts to NOK 70 ...    neutral      1

[1264 rows x 3 columns]

In [60]:
 # Financial data
df_twe = pd.DataFrame(twitter_news['train'])
df_twe_test = pd.DataFrame(twitter_news['validation'])
df_twe
#  0 - Negative
# 1 - positive
# 2 - neutral

                                                   text  label
0     $BYND - JPMorgan reels in expectations on Beyo...      0
1     $CCL $RCL - Nomura points to bookings weakness...      0
2     $CX - Cemex cut at Credit Suisse, J.P. Morgan ...      0
3     $ESS: BTIG Research cuts to Neutral https://t....      0
4     $FNKO - Funko slides after Piper Jaffray PT cu...      0
...                                                 ...    ...
9538  The Week's Gainers and Losers on the Stoxx Eur...      2
9539  Tupperware Brands among consumer gainers; Unil...      2
9540  vTv Therapeutics leads healthcare gainers; Myo...      2
9541    WORK, XPO, PYX and AMKR among after hour movers      2
9542             YNDX, I, QD and OESX among tech movers      2

[9543 rows x 2 columns]

In [61]:
# Since the data set is converted into data from successfully now refurnishing the labels

In [62]:
df_fin[['label','label_text']].value_counts()
# for financial data -
# 0 = negative ,
# 1 = neutral,
# 2 = positive

label  label_text
1      neutral       779
2      positive      320
0      negative      165
Name: count, dtype: int64

In [64]:
# Assigning same labels to twitter data

df_twe['label'].value_counts()
df_twe['label'] = df_twe['label'].map({0 : 0 ,
                                       1 : 2,
                                       2 : 1})
df_twe['label'].value_counts()

label
1    6178
2    1923
0    1442
Name: count, dtype: int64

In [65]:
# Doing same for test data -

df_twe_test['label'].value_counts()
df_twe_test['label'] = df_twe_test['label'].map({0 : 0 ,
                                       1 : 2,
                                       2 : 1})
df_twe_test['label'].value_counts()

label
1    1566
2     475
0     347
Name: count, dtype: int64

In [72]:
# Combining the financial data including test and train
df1 = pd.concat([df_fin,df_fin_test],axis=0)
df1.sample()

                                                  text label_text  label
983  Apartments of YIT Home may be purchased in 5 r...    neutral      1

In [73]:
df2 = pd.concat([df_twe,df_twe_test],axis=0)
df2.sample()

                                                   text  label
2295  $AAPL (+0.2% pre) Apple to expand operations i...      2

In [87]:
df2['label_text'] = df2['label'].map({1: 'neutral',
                                      2 : 'positive',
                                      0 : 'negative'})
df2.columns
df2 = df2[['text', 'label_text', 'label']]

In [89]:
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)

In [94]:
df1.to_csv('Financial_sentiment_data.csv')
df2.to_csv('Financial_tweets_sentiment_data.csv')

In [98]:
# Combining both the data
df = pd.concat([df1,df2],axis=0).reset_index(drop = True)
idx = df.index
# shuffling the data

In [106]:
np.random.seed(45)
idx = np.random.permutation(idx)
df = df.loc[idx,:].reset_index(drop = True)

In [108]:
df.to_csv('Combined_financial_sentiment_analysis_data.csv')